services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    env_file:
      ./env/mysql.env
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
      - ./wordpress_db.sql:/docker-entrypoint-initdb.d/wordpress_db.sql
    networks:
      - wordpress_network
  
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    env_file:
      - ./env/wordpress.env
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress:
  db: